"""add_sambanova_tables

Revision ID: a1b2c3d4e5f6
Revises: f1a2b3c4d5e6
Create Date: 2024-12-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create todos_sambanova table
    op.create_table('todos_sambanova',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('priority', sa.String(), server_default=sa.text('medium'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_sambanova_id'), 'todos_sambanova', ['id'], unique=False)
    op.create_index(op.f('ix_todos_sambanova_title'), 'todos_sambanova', ['title'], unique=False)

    # Create reminders_sambanova table
    op.create_table('reminders_sambanova',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reminder_text', sa.String(), nullable=False),
    sa.Column('importance', sa.String(), server_default=sa.text('medium'), nullable=False),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_sambanova_id'), 'reminders_sambanova', ['id'], unique=False)

    # Create calendar_events_sambanova table
    op.create_table('calendar_events_sambanova',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_from', sa.DateTime(), nullable=False),
    sa.Column('event_to', sa.DateTime(), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_sambanova_id'), 'calendar_events_sambanova', ['id'], unique=False)

    # Create call_recordings_sambanova table
    op.create_table('call_recordings_sambanova',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('call_sid', sa.String(), nullable=False),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('recording_path', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'completed'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_index(op.f('ix_call_recordings_sambanova_id'), 'call_recordings_sambanova', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_recordings_sambanova_id'), table_name='call_recordings_sambanova')
    op.drop_table('call_recordings_sambanova')
    
    op.drop_index(op.f('ix_calendar_events_sambanova_id'), table_name='calendar_events_sambanova')
    op.drop_table('calendar_events_sambanova')
    
    op.drop_index(op.f('ix_reminders_sambanova_id'), table_name='reminders_sambanova')
    op.drop_table('reminders_sambanova')
    
    op.drop_index(op.f('ix_todos_sambanova_title'), table_name='todos_sambanova')
    op.drop_index(op.f('ix_todos_sambanova_id'), table_name='todos_sambanova')
    op.drop_table('todos_sambanova')
    # ### end Alembic commands ###
